[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "patchtree"
description = "generate clean patches for external source trees"
version = "1.0.0"
authors = [
	{ name="Loek Le Blansch", email="loek.le-blansch.pv@renesas.com" },
]
readme = "readme.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["license"]
dependencies = [
	"jinja2",
	"PyYAML",
]

[project.urls]
Homepage = "https://github.com/renesas/patchtree"

[project.scripts]
patchtree = "patchtree.cli:main"

[tool.black]
line-length = 95
